<?php

declare(strict_types=1);

namespace MailerPress\Services;

\defined('ABSPATH') || exit;

/**
 * File logger for low-level debugging (send queue, batches, cleanup).
 *
 * Security contract:
 *  - nothing is ever written unless WP_DEBUG_LOG is enabled in wp-config.php;
 *  - files live in a dedicated uploads sub-directory whose name is salted with the site's
 *    keys (unguessable on servers that ignore .htaccess) and protected by .htaccess + index.php;
 *  - email addresses must be masked with maskEmail() before being logged.
 *
 * The legacy, world-readable wp-content/mailerpress-logs/ directory is purged on upgrade.
 */
final class DebugFileLogger
{
    private const DIR_SLUG = 'mailerpress-logs';

    private static ?string $directory = null;

    /**
     * Logging is opt-in through WP_DEBUG_LOG (true, or a custom log path string as WordPress
     * itself accepts).
     */
    public static function isEnabled(): bool
    {
        if (!\defined('WP_DEBUG_LOG')) {
            return false;
        }

        $value = \constant('WP_DEBUG_LOG');

        return true === $value || (\is_string($value) && '' !== trim($value));
    }

    /**
     * Append a line to $file (basename only) inside the protected log directory.
     */
    public static function write(string $file, string $message, array $context = []): void
    {
        if (!self::isEnabled()) {
            return;
        }

        $directory = self::getDirectory();
        if (null === $directory) {
            return;
        }

        $file = sanitize_file_name(basename($file));
        if ('' === $file || '.' === $file[0]) {
            return;
        }

        $contextStr = !empty($context) ? ' | Context: ' . wp_json_encode($context) : '';
        $line = sprintf("[%s] %s%s\n", current_time('mysql'), $message, $contextStr);

        @file_put_contents($directory . '/' . $file, $line, FILE_APPEND | LOCK_EX);
    }

    /**
     * Mask an email address for logging: "j***@example.com".
     */
    public static function maskEmail(string $email): string
    {
        $email = trim($email);
        $at = strrpos($email, '@');

        if (false === $at || 0 === $at) {
            return '' === $email ? '' : '***';
        }

        return substr($email, 0, 1) . '***' . substr($email, $at);
    }

    /**
     * Protected log directory, created on demand. Null when logging is disabled or the
     * directory cannot be created.
     */
    public static function getDirectory(): ?string
    {
        if (!self::isEnabled()) {
            return null;
        }

        if (null !== self::$directory) {
            return self::$directory;
        }

        $uploads = wp_upload_dir(null, false);
        if (!empty($uploads['error']) || empty($uploads['basedir'])) {
            return null;
        }

        $suffix = substr(wp_hash(self::DIR_SLUG . '|' . get_current_blog_id()), 0, 16);
        $directory = trailingslashit($uploads['basedir']) . self::DIR_SLUG . '-' . $suffix;

        if (!is_dir($directory) && !wp_mkdir_p($directory)) {
            return null;
        }

        self::protectDirectory($directory);

        if (!is_writable($directory)) {
            return null;
        }

        self::$directory = $directory;

        return $directory;
    }

    /**
     * Deny direct HTTP access to a directory (Apache 2.2/2.4) and prevent listings.
     */
    public static function protectDirectory(string $directory): void
    {
        $directory = untrailingslashit($directory);

        $htaccess = $directory . '/.htaccess';
        if (!file_exists($htaccess)) {
            @file_put_contents(
                $htaccess,
                "# Generated by MailerPress: never serve these files.\n"
                . "<IfModule mod_authz_core.c>\n    Require all denied\n</IfModule>\n"
                . "<IfModule !mod_authz_core.c>\n    Order deny,allow\n    Deny from all\n</IfModule>\n"
            );
        }

        $index = $directory . '/index.php';
        if (!file_exists($index)) {
            @file_put_contents($index, "<?php\n// Silence is golden.\n");
        }
    }

    /**
     * Remove the legacy world-readable log directory created by previous versions
     * (wp-content/mailerpress-logs/). Only MailerPress log files are removed.
     */
    public static function purgeLegacyDirectory(): void
    {
        $legacy = untrailingslashit(WP_CONTENT_DIR) . '/' . self::DIR_SLUG;

        if (!is_dir($legacy)) {
            return;
        }

        foreach ((array) glob($legacy . '/*.log') as $file) {
            if (\is_string($file) && is_file($file)) {
                @unlink($file);
            }
        }

        foreach (['.htaccess', 'index.php', 'index.html'] as $extra) {
            if (is_file($legacy . '/' . $extra)) {
                @unlink($legacy . '/' . $extra);
            }
        }

        @rmdir($legacy);
    }

    /**
     * Make sure the shared uploads/mailerpress-logs directory used by older import and repair
     * logs cannot be listed or served.
     */
    public static function protectLegacyUploadsDirectory(): void
    {
        $uploads = wp_upload_dir(null, false);
        if (!empty($uploads['error']) || empty($uploads['basedir'])) {
            return;
        }

        $directory = trailingslashit($uploads['basedir']) . self::DIR_SLUG;
        if (is_dir($directory)) {
            self::protectDirectory($directory);
        }
    }
}
